@url = https://z67jp4ep9c.execute-api.us-west-2.amazonaws.com/prod/
@token = <your-cognito-id-token>

GET {{url}}/spaceFinder/
Authorization: Bearer {{token}}
###

GET {{url}}/spaceFinder/?id=<space-id>
Authorization: Bearer {{token}}
###

POST {{url}}/spaceFinder
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "location": "Los Angeles",
    "name": "Hollywood Sign"
}
###

PUT {{url}}/spaceFinder/?id=<space-id>
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "location": "Los Angeles updated",
    "name": "Hollywood Sign updated"
}
###

DELETE {{url}}/spaceFinder/?id=<space-id>
Authorization: Bearer {{token}}
###
